// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekevswdntuwroqeactfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrZXZzd2RudHV3cm9xZWFjdGZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3OTEyOTEsImV4cCI6MjA2ODM2NzI5MX0.WJHC_RXIy0yloJa9R1Ess4-P-S4YSFtR-pl63HodlHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});